import { Command } from "commander";
import { existsSync, writeFileSync } from "fs";
import { join } from "path";
import { createRequire } from "module";
import { generateLLMContext } from "./llm-context.js";

const require = createRequire(import.meta.url);
const packageJson = require("../../package.json");

const HUSKY_MD_FILENAME = "HUSKY.md";

function generateHuskyMdContent(): string {
  const timestamp = new Date().toISOString();
  const cliRef = generateLLMContext();
  
  return `<!-- 
  Auto-generated by husky init (v${packageJson.version})
  Generated: ${timestamp}
  
  This file instructs AI coding agents to use the Husky CLI.
  Update with: husky init --force
-->

${cliRef}

---

## Standard Workflow for AI Agents

### On Session Start
\`\`\`bash
husky config test    # Verify API connection
husky worker whoami  # Confirm worker identity
\`\`\`

### When Working on a Task
\`\`\`bash
# 1. Get task details
husky task get <id>

# 2. Start the task (creates isolated worktree)
husky task start <id>

# 3. CD into the worktree directory (MANDATORY)
cd <worktree-path>  # Path shown in task start output

# 4. Report progress as you work
husky task message <id> "Analyzing codebase..."
husky task message <id> "Implementing feature X..."

# 5. When done, create PR and complete
husky worktree pr <worktree-name> -t "feat: description"
husky task done <id> --pr <pr-url>
\`\`\`

**IMPORTANT:** After \`husky task start\`, you MUST \`cd\` into the worktree directory before making any code changes.

### When Handling Customer Support
\`\`\`bash
# 1. Get full customer context
husky biz customers 360 <email>

# 2. Check relevant tickets
husky biz tickets search "<customer-email>"

# 3. Check order history if needed
husky biz orders search "<order-id-or-email>"

# 4. Reply with context
husky biz tickets reply <ticket-id> "Your response..."
\`\`\`
`;
}

export const initCommand = new Command("init")
  .description("Initialize Husky in the current directory (creates HUSKY.md)")
  .option("-f, --force", "Overwrite existing HUSKY.md")
  .option("-q, --quiet", "Suppress output")
  .action((options) => {
    const targetPath = join(process.cwd(), HUSKY_MD_FILENAME);
    
    if (existsSync(targetPath) && !options.force) {
      console.error(`Error: ${HUSKY_MD_FILENAME} already exists.`);
      console.error("Use --force to overwrite.");
      process.exit(1);
    }
    
    const content = generateHuskyMdContent();
    writeFileSync(targetPath, content);
    
    if (!options.quiet) {
      console.log(`✓ Created ${HUSKY_MD_FILENAME}`);
      console.log("");
      console.log("  This file instructs AI agents to use the Husky CLI.");
      console.log("  Commit it to your repository so all agents see it.");
      console.log("");
      console.log("  Update with: husky init --force");
    }
  });
